### ISSUE TITLE
oftcdns Not Starting

### ISSUE THREAD

**Issue by Joah** [oftc/oftc-tools#1]
When trying to run oftcdns on Debian, Ubuntu, or Arch Linux systems, a friend and I experience the following errors: http://gopaste.it/pmq0 (taken from the Debian 6 64-bit install). We have been unable to figure out what causes this, though we have had it run properly in the past.

**Comment by df7cb** [comment]
Hi,

oftcdns development has stalled long ago, and OFTC has switched to a different solution now.

Closing this issue now.
