### ISSUE TITLE
Thoughts on offering a message board service?

### ISSUE THREAD

**Issue by ebekker** [oftc/oftc-tools#2]
Not sure if this is the right channel for proposing/discussing this, but has OFTC ever considered offering message board services?

Something like hosting [Discourse](http://www.discourse.org/) for FOSS projects seems like it would be in the same wheelhouse as the current set of services that are already being offered or planned.

**Comment by df7cb** [comment]
Hi,

Discourse looks like a nice piece of software, but we OFTC people are coming from an IRC background, so I'd be very surprised of anyone here would fancy running web forums.

Thanks for the suggestion, though. (And in the meantime, I've created a "catch-all" repository for issues that don't fit elsewhere -- https://github.com/oftc/oftc).
